# Google Cloud App Engine configuration
# Alternative deployment option to Cloud Run

runtime: nodejs18

env: standard

instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

# Environment variables (configure these in GCP Console or Secret Manager)
env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  # Add other non-sensitive environment variables here
  # For sensitive data, use Google Cloud Secret Manager

# VPC connector for private MongoDB access (if needed)
# vpc_access_connector:
#   name: projects/YOUR_PROJECT_ID/locations/YOUR_REGION/connectors/YOUR_CONNECTOR

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
